"""rename_video_table_to_videos

Revision ID: bf53b595ab74
Revises: d1d1d81f68d2
Create Date: 2026-02-17 23:47:58.680318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'bf53b595ab74'
down_revision = 'd1d1d81f68d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(length=50), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=True),
    sa.Column('audio_codec', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('video')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fps', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codec', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('bitrate', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('has_audio', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('audio_codec', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='video_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='video_pkey')
    )
    op.drop_table('videos')
    # ### end Alembic commands ###
